[package]
name = "radiant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["full"] }

[[example]]
name = "client"
