[workspace]
resolver = "2"
members = ["radiant-*", "examples/*"]

[workspace.dependencies]
bincode = "1.3"
bytes = "1.5"
prost = "0.12"
prost-types = "0.12"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35", features = ["full"] }
tonic = "0.11"
tonic-build = "0.11"
