[package]
name = "radiant-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode.workspace = true
serde.workspace = true
tonic.workspace = true

radiant-protocol = { path = "../radiant-protocol" }
anyhow = "1.0"
